name: wiki_race
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  firebase_auth: ^3.11.0
  firebase_core: ^1.24.0
  google_fonts: ^3.0.1
  firebase_database: ^9.1.6
  cloud_firestore: ^3.5.0
  json_annotation: ^4.7.0
  http: ^0.13.5
  flutter_typeahead: ^4.1.1
  meta: ^1.8.0
  beamer: ^1.5.3
  flutter_svg: ^1.1.5
  webviewx: ^0.2.1
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  json_serializable: ^6.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/wikipedia.png