// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwWjZCHz1rLFdonI6kUvwm_wFFKh2BqbE',
    appId: '1:820976233175:web:feadc1085636a285431e92',
    messagingSenderId: '820976233175',
    projectId: 'wiki-race-ae773',
    authDomain: 'wiki-race-ae773.firebaseapp.com',
    databaseURL: 'https://wiki-race-ae773-default-rtdb.firebaseio.com',
    storageBucket: 'wiki-race-ae773.appspot.com',
    measurementId: 'G-2S2NDBPZGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbhDsYa8hOhVj0SfDcPCZjPp3vYJ1mPXQ',
    appId: '1:820976233175:android:27ef7d1dc363737a431e92',
    messagingSenderId: '820976233175',
    projectId: 'wiki-race-ae773',
    databaseURL: 'https://wiki-race-ae773-default-rtdb.firebaseio.com',
    storageBucket: 'wiki-race-ae773.appspot.com',
  );
}
